# Generated by Django 4.1 on 2022-09-01 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id_cart', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('total_cart', models.IntegerField()),
                ('customers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='toko.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id_transaksi', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('qty_trans', models.IntegerField()),
                ('total', models.IntegerField()),
                ('carts', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='toko.keranjang')),
                ('customers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='toko.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_Produk', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nama_Produk', models.CharField(max_length=40)),
                ('harga', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('kategoris', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='toko.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='KeranjangDetail',
            fields=[
                ('id_keranjang_detail', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('qty_cart', models.IntegerField()),
                ('total_harga', models.IntegerField()),
                ('carts', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='toko.keranjang')),
                ('products', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='toko.produk')),
            ],
            options={
                'db_table': 'toko_apps',
            },
        ),
    ]
